### ISSUE TITLE
Template error while templating string: no filter named 'search'

### ISSUE THREAD

**Issue by adrianovieira** [trombik/ansible-role-opendistroforelasticsearch#11]
##### ISSUE TYPE

 - Bug Report

##### ROLE VERSION

```
[WARNING]: - trombik.opendistroforelasticsearch (1.1.1) is already installed
[WARNING]: - trombik.java (2.0.0) is already installed
[WARNING]: - trombik.sysctl (1.0.2) is already installed
[WARNING]: - trombik.redhat_repo (2.0.1) is already installed
[WARNING]: - trombik.x509_certificate (2.1.1) is already installed
```

##### CONFIGURATION

none

##### OS / ENVIRONMENT

CEntOS-7 (guest)
Fedora-32 (host)
Ansible 2.9.11 <details>
```
ansible-playbook 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/adriano.vieira/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, Aug 12 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```
</details>

##### SUMMARY

Trying to run an simple sample playbook using yours roles.

```
ansible-playbook  --ask-pass -u root playbook.yml -i defaults -i inventory 
```

##### STEPS TO REPRODUCE

playbook

```yaml
- hosts: opendistroforelasticsearch
  roles:
    - role: trombik.redhat_repo
    - role: trombik.java
    - role: trombik.sysctl
    - role: trombik.opendistroforelasticsearch
```

default vars

```yaml
---
opendistroforelasticsearch:
  vars:
  # exactly the same of your's "readme" example
```

guest server

```yaml
---
opendistroforelasticsearch:
  children:
    master-eligible:
      hosts:
        node-01.hackerlab:
```

logs

```
[..]

TASK [trombik.opendistroforelasticsearch : Register installed plugins] *************************************************
ok: [node-02.hackerlab]

TASK [trombik.opendistroforelasticsearch : Create plugins directory] **************************************************
ok: [node-01.hackerlab]

TASK [trombik.opendistroforelasticsearch : Install plugins] **************************************************************
fatal: [node-01.hackerlab]: FAILED! => {"msg": "The conditional check 'not (shell_output.stdout | search(item['name']))' failed. The error was: template error while templating string: no filter named 'search'. String: {% if not (shell_output.stdout | search(item['name'])) %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/adriano.vieira/.ansible/roles/trombik.opendistroforelasticsearch/tasks/main.yml': line 83, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install plugins\n  ^ here\n"}

[..]
```

##### EXPECTED RESULTS

Install Open Distro for Elasticsearch on a CEntOS-7 with all default values

##### ACTUAL RESULTS

The error was: template error while templating string: no filter named 'search'

**Comment by trombik** [comment]
what happens if you switch to `master`?

```yaml
- name: trombik.opendistroforelasticsearch
  src: https://github.com/trombik/ansible-role-opendistroforelasticsearch
  version: master
```

3cba9c33e3ce8f60b8d73a1616fba30baffaf661 should have fixed it. as for new release, the role needs fixes for Ubuntu (CentOS should work fine, confirmed in my test).
